name: ballet
favicon: null
layout_spectrum: 0.57545
typography_spectrum: 0.5680777241941541
title: 'Ballet | Information, tips and pictures'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9c6b5'
    - '#d8b691'
    - '#b59475'
    - '#c0a68f'
  brandStrength: 0.5
  lightness: 0.23714023479260504
  saturation: 0.7976430761627853
  rhythmicContrast: 0.5783291573170573
purpose: []
