name: ballet
favicon: null
layout_spectrum: 0.4460830888710916
typography_spectrum: 0.5680777241941541
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.05145634850487113
  lightness: 0.23714023479260504
  saturation: 0.7976430761627853
  rhythmicContrast: 0.5783291573170573
purpose: []
